### PR TITLE
removed every occurrence of any lg:pb-* from line  232 to 646

### LINKED ISSUE #56: Consistent tile padding for small and large screens
remove every occurrence of any `lg:pb-*` class from `static/index.html`, starting with line 232:

https://github.com/jofas/jofas.github.io/blob/ae591eed0c2585b1626fefeddb069f7631614c4a/static/index.html#L232

ending at line 646:

https://github.com/jofas/jofas.github.io/blob/ae591eed0c2585b1626fefeddb069f7631614c4a/static/index.html#L646

### LINKED ISSUE #57: Hero landing image same size and padding on small and large screens
Remove any  `lg:*` class here:

https://github.com/jofas/jofas.github.io/blob/ae591eed0c2585b1626fefeddb069f7631614c4a/static/index.html#L143-L145

### LINKED ISSUE #60: Bug: `Key Skills` section having padding instead of margin
Replace `px-8` class with `mx-8`:

https://github.com/jofas/jofas.github.io/blob/ae591eed0c2585b1626fefeddb069f7631614c4a/static/index.html#L223

### PR DESCRIPTION
**Pull request by RajeevDash007**
* Fixes #56 
* Fixes #57
* Fixes #60

### CODE REVIEW

**Comment by jofas** [comment]
Thanks, looks good to me. Just a little tip, if you add a sentence `fixes #{number of issue}`, GitHub automatically creates a link between PR and issue, closing the issue automatically once the PR is merged. In this case:

* Fixes #56 
* Fixes #57
* Fixes #60

**Comment by RajeevDash007** [comment]
Thanks for the tip

**Comment by jofas** [comment]
Thanks for the work, much appreciated

**Comment by RajeevDash007** [comment]
I will look forward to work with you .

**Pull request merged**
